# Generated by Django 4.2.1 on 2023-05-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUSocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_name', models.CharField(help_text='Введите название сокета', max_length=15, verbose_name='Сокет')),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название накопителя', max_length=200, verbose_name='Название накопителя')),
                ('capacity', models.CharField(help_text='Введите ёмкость накопителя', max_length=10, verbose_name='Ёмкость накопителя')),
                ('speed', models.CharField(help_text='Введите скорость чтения/записи', max_length=10, verbose_name='Скорость чтения/записи')),
            ],
        ),
        migrations.CreateModel(
            name='type_RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Введите тип оперативной памяти', max_length=10, verbose_name='Тип оперативной памяти')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название видеокарты', max_length=200, verbose_name='Название видеокарты')),
                ('video_memory', models.CharField(help_text='Введите объём видеопамяти', max_length=4, verbose_name='Объём памяти')),
                ('memoty_type', models.CharField(help_text='Введите тип видеопамяти', max_length=10, verbose_name='Тим видеопамяти')),
                ('memory_frequency', models.CharField(help_text='Введите частоту памяти', max_length=6, verbose_name='Частота памяти')),
                ('connection_type', models.CharField(help_text='Введите тип подключения', max_length=200, verbose_name='Тип подключения')),
                ('recommended_psu_wattage', models.CharField(help_text='Введите рекомендуемую мощность БП', max_length=5, verbose_name='Рекомендуемая мощность БП')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название оперативное памяти', max_length=200, verbose_name='Название оперативной памяти')),
                ('memory', models.CharField(help_text='Введите объём модуля ОП', max_length=3, verbose_name='Объём модуля ОП')),
                ('clock_frequency', models.CharField(help_text='Введите тактовую частоту', max_length=10, verbose_name='Тактовая частота')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC_Components.type_ram', verbose_name='Тип оперативной памяти')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название материнской платы', max_length=200, verbose_name='Название материнской платы')),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC_Components.type_ram', verbose_name='Тип оперативной памяти')),
                ('socket_motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC_Components.cpusocket', verbose_name='Сокет')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название процессора', max_length=200, verbose_name='Название процессора')),
                ('nuclei', models.CharField(help_text='Введите количество ядер', max_length=15, verbose_name='Количество ядер')),
                ('clock_frequency', models.CharField(help_text='Введите тактовую частоту', max_length=10, verbose_name='Тактовая частота')),
                ('socket_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC_Components.cpusocket', verbose_name='Сокет')),
            ],
        ),
    ]
