# Generated by Django 4.2.1 on 2023-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название блока питания', max_length=200, verbose_name='Название блока питания')),
                ('power', models.CharField(help_text='Введите мощность БП', max_length=20, verbose_name='Мощность БП')),
                ('efficiency_standard', models.CharField(help_text='Введите стандарт эффективности', max_length=50, verbose_name='Стандарт эффективности')),
                ('motherboard_connector_type', models.CharField(help_text='Введите тип разъёма для мат. платы', max_length=50, verbose_name='Тип разъёма для мат. платы')),
                ('quantityCPU', models.CharField(help_text='Введите количество разъёмов 4+4pin CPU', max_length=50, verbose_name='Количество разъёмов 4+4pin CPU')),
                ('quantityPCI_E', models.CharField(help_text='Введите количество разъёмов PCI-E', max_length=50, verbose_name='Количество разъёмов PCI-E')),
            ],
        ),
        migrations.AlterField(
            model_name='ram',
            name='memory',
            field=models.CharField(help_text='Введите объём модуля ОП', max_length=10, verbose_name='Объём модуля ОП'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='speed',
            field=models.CharField(help_text='Введите скорость чтения/записи', max_length=25, verbose_name='Скорость чтения/записи'),
        ),
        migrations.AlterField(
            model_name='videocards',
            name='connection_type',
            field=models.CharField(help_text='Введите тип подключения', max_length=50, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='videocards',
            name='memory_frequency',
            field=models.CharField(help_text='Введите частоту памяти', max_length=10, verbose_name='Частота памяти'),
        ),
        migrations.AlterField(
            model_name='videocards',
            name='recommended_psu_wattage',
            field=models.CharField(help_text='Введите рекомендуемую мощность БП', max_length=10, verbose_name='Рекомендуемая мощность БП'),
        ),
        migrations.AlterField(
            model_name='videocards',
            name='video_memory',
            field=models.CharField(help_text='Введите объём видеопамяти', max_length=10, verbose_name='Объём памяти'),
        ),
    ]
